spring:
  application:
    name: bulk-util
  datasource:
    url: 'jdbc:h2:mem:datasetdb'
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
